//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niranjan_Book_Shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Niranjan_Book_shopEntities2 : DbContext
    {
        public Niranjan_Book_shopEntities2()
            : base("name=Niranjan_Book_shopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<products__image> products__image { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
