//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niranjan_Book_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class products__image
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public Nullable<decimal> p_price { get; set; }
        public Nullable<int> p_qty { get; set; }
        public string p_details { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> o_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual Order Order { get; set; }
    }
}
